import { useState } from 'react'
import { Briefcase, GraduationCap, Award, FolderGit2, Sparkles, User, Wrench, Target } from 'lucide-react'
import { useResumeDraft } from '@/hooks/useResumeDraft'
import { Repeatable } from '@/components/forms/repeatable'
import { BulletsEditorWithAI } from '@/components/forms/bullets-editor-with-ai'
import { TextField, MonthField, TextAreaField, TagsInput } from '@/components/forms/form-field'
import { EditorSection } from '@/components/editor/editor-section'
import { WritingActions } from '@/components/editor/writing-actions'
import { ImproveBulletButton } from '@/components/editor/improve-bullet-button'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { Textarea } from '@/components/ui/textarea'
import { Input } from '@/components/ui/input'
import { aiProvider } from '@/services/ai/client'
import { useUiStore } from '@/store/uiStore'
import { SKILL_CATEGORIES } from '@/data/constants'
import { uid } from '@/lib/utils'
import type {
  AchievementItem,
  CertificationItem,
  EducationItem,
  ExperienceItem,
  ProjectItem,
  SkillGroup,
} from '@/types/resume'

/* ─── Personal ───────────────────────────────────────────────────────── */

export function PersonalSection() {
  const { data, patch } = useResumeDraft()
  if (!data) return null
  const p = data.personal
  const set = (patchPart: Partial<typeof p>) => patch({ personal: { ...p, ...patchPart } })
  const setContact = (patchPart: Partial<typeof p.contact>) =>
    patch({ personal: { ...p, contact: { ...p.contact, ...patchPart } } })

  return (
    <EditorSection
      title="Personal Information"
      icon={<User className="size-4" />}
      badge={p.fullName ? 'Complete' : 'Incomplete'}
    >
      <div className="grid gap-4 sm:grid-cols-2">
        <TextField label="Full Name" value={p.fullName} onChange={(e) => set({ fullName: e.target.value })} />
        <TextField label="Professional Title" value={p.professionalTitle} onChange={(e) => set({ professionalTitle: e.target.value })} />
        <TextField label="Email" type="email" value={p.contact.email} onChange={(e) => setContact({ email: e.target.value })} />
        <TextField label="Phone" value={p.contact.phone} onChange={(e) => setContact({ phone: e.target.value })} />
        <TextField label="Location" value={p.contact.location} onChange={(e) => setContact({ location: e.target.value })} />
        <TextField label="LinkedIn" value={p.contact.linkedin} onChange={(e) => setContact({ linkedin: e.target.value })} />
        <TextField label="GitHub" value={p.contact.github} onChange={(e) => setContact({ github: e.target.value })} />
        <TextField label="Portfolio" value={p.contact.portfolio} onChange={(e) => setContact({ portfolio: e.target.value })} />
      </div>
      <div className="mt-4 flex items-center gap-3">
        <Switch
          checked={data.settings.includePhoto}
          onCheckedChange={(v) => patch({ settings: { ...data.settings, includePhoto: v } })}
          label="Include photo"
        />
        <span className="text-sm text-muted">Include photo on resume</span>
      </div>
    </EditorSection>
  )
}

/* ─── Summary ────────────────────────────────────────────────────────── */

export function SummarySection() {
  const { data, patch } = useResumeDraft()
  const toast = useUiStore((s) => s.toast)
  const [loading, setLoading] = useState(false)
  if (!data) return null

  const generate = async () => {
    setLoading(true)
    try {
      const res = await aiProvider.generate({
        resume: data,
        action: 'generate-summary',
        jobDescription: data.targetJob.jobDescription,
      })
      if (res.summary) {
        patch({ summary: res.summary, summarySource: 'ai' })
        toast({ title: 'Summary generated', variant: 'success' })
      }
    } catch (err) {
      toast({
        title: 'Could not generate summary',
        description: err instanceof Error ? err.message : 'The AI service is temporarily unavailable.',
        variant: 'error',
      })
    } finally {
      setLoading(false)
    }
  }

  return (
    <EditorSection
      title="Professional Summary"
      subtitle={data.summarySource === 'ai' ? 'Generated by AI' : data.summary ? 'Manually written' : 'Empty'}
      icon={<Sparkles className="size-4" />}
      badge={data.summary ? 'Complete' : 'Incomplete'}
    >
      <div className="mb-3 flex items-center justify-between gap-3">
        <Button type="button" variant="outline" size="sm" onClick={() => void generate()} loading={loading}>
          <Sparkles className="size-3.5" />
          {loading ? 'Generating…' : 'Generate Summary'}
        </Button>
        <WritingActions
          text={data.summary}
          role={data.targetJob.role}
          context={resumeTextContext(data)}
          onResult={(t) => patch({ summary: t, summarySource: 'manual' })}
        />
      </div>
      <Textarea
        rows={5}
        value={data.summary}
        onChange={(e) => patch({ summary: e.target.value, summarySource: 'manual' })}
        placeholder="Write a concise summary grounded in your actual experience…"
      />
    </EditorSection>
  )
}

/* ─── Experience ─────────────────────────────────────────────────────── */

export function ExperienceSection() {
  const { data, patch } = useResumeDraft()
  const items = data?.experience ?? []

  const add = () =>
    patch({
      experience: [...items, { id: uid('exp'), company: '', jobTitle: '', location: '', startDate: '', endDate: '', current: false, summary: '', bullets: [], technologies: [] }],
    })
  const remove = (id: string) => patch({ experience: items.filter((e) => e.id !== id) })
  const change = (id: string, p: Partial<ExperienceItem>) =>
    patch({ experience: items.map((e) => (e.id === id ? { ...e, ...p } : e)) })

  return (
    <EditorSection
      title="Work Experience"
      icon={<Briefcase className="size-4" />}
      badge={String(items.length)}
    >
      <Repeatable
        items={items}
        onAdd={add}
        onRemove={remove}
        onChange={(id, p) => change(id, p)}
        addLabel="Add Experience"
        emptyLabel="No experience yet."
        render={(item) => (
          <>
            <div className="grid gap-4 sm:grid-cols-2">
              <TextField label="Job Title" value={item.jobTitle} onChange={(e) => change(item.id, { jobTitle: e.target.value })} />
              <TextField label="Company" value={item.company} onChange={(e) => change(item.id, { company: e.target.value })} />
              <TextField label="Location" optional value={item.location} onChange={(e) => change(item.id, { location: e.target.value })} />
              <div className="flex items-end gap-3 pb-2">
                <Switch
                  checked={item.current}
                  onCheckedChange={(v) => change(item.id, { current: v, endDate: v ? '' : item.endDate })}
                  label="Current role"
                />
                <span className="text-xs text-muted">Current</span>
              </div>
              <MonthField label="Start Date" value={item.startDate ?? ''} onChange={(e) => change(item.id, { startDate: e.target.value })} />
              <MonthField label="End Date" optional disabled={item.current} value={item.current ? '' : (item.endDate ?? '')} onChange={(e) => change(item.id, { endDate: e.target.value })} />
              <div className="sm:col-span-2">
                <TextAreaField label="Role Summary" optional value={item.summary} onChange={(e) => change(item.id, { summary: e.target.value })} />
              </div>
            </div>
            <div>
              <p className="mb-1.5 text-sm font-medium text-muted">Technologies</p>
              <TagsInput value={item.technologies} onChange={(v) => change(item.id, { technologies: v })} placeholder="e.g. React, TypeScript…" ariaLabel="Technologies" />
            </div>
            <div>
              <div className="mb-2 flex items-center justify-between">
                <p className="text-sm font-medium text-muted">Bullets</p>
                <ImproveBulletButton
                  bullet={item.bullets.join(' ')}
                  context={{ jobTitle: item.jobTitle, company: item.company, role: data?.targetJob.role, technologies: item.technologies }}
                  jobDescription={data?.targetJob.jobDescription}
                  label="Improve all with AI"
                  onImproved={(improved) => change(item.id, { bullets: item.bullets.map(() => improved) })}
                />
              </div>
              <BulletsEditorWithAI
                value={item.bullets}
                onChange={(v) => change(item.id, { bullets: v })}
                context={{ jobTitle: item.jobTitle, company: item.company, role: data?.targetJob.role, technologies: item.technologies }}
                jobDescription={data?.targetJob.jobDescription}
              />
            </div>
          </>
        )}
      />
    </EditorSection>
  )
}

/* ─── Education ──────────────────────────────────────────────────────── */

export function EducationSection() {
  const { data, patch } = useResumeDraft()
  const items = data?.education ?? []

  const add = () =>
    patch({ education: [...items, { id: uid('edu'), institution: '', degree: '', fieldOfStudy: '', startDate: '', endDate: '', gpa: '', coursework: [] }] })
  const remove = (id: string) => patch({ education: items.filter((e) => e.id !== id) })
  const change = (id: string, p: Partial<EducationItem>) =>
    patch({ education: items.map((e) => (e.id === id ? { ...e, ...p } : e)) })

  return (
    <EditorSection title="Education" icon={<GraduationCap className="size-4" />} badge={String(items.length)}>
      <Repeatable
        items={items}
        onAdd={add}
        onRemove={remove}
        onChange={(id, p) => change(id, p)}
        addLabel="Add Education"
        emptyLabel="No education yet."
        render={(item) => (
          <>
            <div className="grid gap-4 sm:grid-cols-2">
              <TextField label="Institution" value={item.institution} onChange={(e) => change(item.id, { institution: e.target.value })} />
              <TextField label="Degree" value={item.degree} onChange={(e) => change(item.id, { degree: e.target.value })} />
              <TextField label="Field of Study" optional value={item.fieldOfStudy} onChange={(e) => change(item.id, { fieldOfStudy: e.target.value })} />
              <TextField label="GPA" optional value={item.gpa} onChange={(e) => change(item.id, { gpa: e.target.value })} />
              <MonthField label="Start Date" value={item.startDate ?? ''} onChange={(e) => change(item.id, { startDate: e.target.value })} />
              <MonthField label="Graduation Date" value={item.endDate ?? ''} onChange={(e) => change(item.id, { endDate: e.target.value })} />
            </div>
            <div>
              <p className="mb-1.5 text-sm font-medium text-muted">Relevant coursework</p>
              <TagsInput value={item.coursework} onChange={(v) => change(item.id, { coursework: v })} placeholder="e.g. Data Structures…" ariaLabel="Coursework" />
            </div>
          </>
        )}
      />
    </EditorSection>
  )
}

/* ─── Skills ─────────────────────────────────────────────────────────── */

export function SkillsSection() {
  const { data, patch } = useResumeDraft()
  if (!data) return null
  const groups = data.skills.technical
  const soft = data.skills.soft

  const setGroups = (next: SkillGroup[]) => patch({ skills: { ...data.skills, technical: next } })
  const setSoft = (next: string[]) => patch({ skills: { ...data.skills, soft: next } })
  const updateGroup = (label: string, skills: string[]) => setGroups(groups.map((g) => (g.label === label ? { ...g, skills } : g)))
  const addGroup = (label: string) => {
    if (groups.some((g) => g.label === label)) return
    setGroups([...groups, { label, skills: [] }])
  }
  const removeGroup = (label: string) => setGroups(groups.filter((g) => g.label !== label))

  return (
    <EditorSection
      title="Skills"
      icon={<Wrench className="size-4" />}
      badge={String(groups.flatMap((g) => g.skills).length)}
    >
      <div className="space-y-3">
        {groups.map((g) => (
          <div key={g.label} className="rounded-md border border-border bg-surface-2/50 p-3">
            <div className="mb-2 flex items-center justify-between">
              <p className="text-xs font-semibold uppercase tracking-wide text-subtle">{g.label}</p>
              <button type="button" onClick={() => removeGroup(g.label)} className="text-xs text-subtle hover:text-danger" aria-label={`Remove ${g.label}`}>
                Remove
              </button>
            </div>
            <TagsInput value={g.skills} onChange={(v) => updateGroup(g.label, v)} placeholder="Type and press Enter…" ariaLabel={`Skills in ${g.label}`} />
          </div>
        ))}
        <div className="flex flex-wrap gap-2">
          {SKILL_CATEGORIES.filter((c) => !groups.some((g) => g.label === c)).map((c) => (
            <button
              key={c}
              type="button"
              onClick={() => addGroup(c)}
              className="focus-ring rounded-md border border-border-strong px-2.5 py-1 text-xs text-muted hover:bg-surface-2 hover:text-foreground"
            >
              + {c}
            </button>
          ))}
        </div>
        <div>
          <p className="mb-1.5 text-sm font-medium text-muted">Soft skills (optional)</p>
          <TagsInput value={soft} onChange={setSoft} placeholder="e.g. Communication…" ariaLabel="Soft skills" />
        </div>
      </div>
    </EditorSection>
  )
}

/* ─── Projects ───────────────────────────────────────────────────────── */

export function ProjectsSection() {
  const { data, patch } = useResumeDraft()
  const items = data?.projects ?? []

  const add = () =>
    patch({ projects: [...items, { id: uid('proj'), name: '', description: '', technologies: [], githubUrl: '', liveUrl: '', bullets: [] }] })
  const remove = (id: string) => patch({ projects: items.filter((x) => x.id !== id) })
  const change = (id: string, p: Partial<ProjectItem>) =>
    patch({ projects: items.map((x) => (x.id === id ? { ...x, ...p } : x)) })

  return (
    <EditorSection title="Projects" icon={<FolderGit2 className="size-4" />} badge={String(items.length)}>
      <Repeatable
        items={items}
        onAdd={add}
        onRemove={remove}
        onChange={(id, p) => change(id, p)}
        addLabel="Add Project"
        emptyLabel="No projects yet."
        render={(item) => (
          <>
            <div className="grid gap-4 sm:grid-cols-2">
              <TextField label="Project Name" value={item.name} onChange={(e) => change(item.id, { name: e.target.value })} />
              <TextField label="GitHub URL" optional value={item.githubUrl} onChange={(e) => change(item.id, { githubUrl: e.target.value })} />
              <div className="sm:col-span-2">
                <TextAreaField label="Description" optional value={item.description} onChange={(e) => change(item.id, { description: e.target.value })} />
              </div>
              <TextField label="Live Demo URL" optional value={item.liveUrl} onChange={(e) => change(item.id, { liveUrl: e.target.value })} />
              <div className="sm:col-span-2">
                <p className="mb-1.5 text-sm font-medium text-muted">Technologies</p>
                <TagsInput value={item.technologies} onChange={(v) => change(item.id, { technologies: v })} placeholder="e.g. React, Node.js…" ariaLabel="Project technologies" />
              </div>
              <div className="sm:col-span-2">
                <BulletsEditorWithAI
                  value={item.bullets}
                  onChange={(v) => change(item.id, { bullets: v })}
                  context={{ jobTitle: item.name, company: 'Personal Project', role: data?.targetJob.role, technologies: item.technologies }}
                  jobDescription={data?.targetJob.jobDescription}
                  label="Key contributions"
                />
              </div>
            </div>
          </>
        )}
      />
    </EditorSection>
  )
}

/* ─── Certifications & Achievements ──────────────────────────────────── */

export function CertificationsSection() {
  const { data, patch } = useResumeDraft()
  const items = data?.certifications ?? []
  const change = (id: string, p: Partial<CertificationItem>) =>
    patch({ certifications: items.map((x) => (x.id === id ? { ...x, ...p } : x)) })

  return (
    <EditorSection title="Certifications" icon={<Award className="size-4" />} badge={String(items.length)}>
      <Repeatable
        items={items}
        onAdd={() => patch({ certifications: [...items, { id: uid('cert'), name: '', organization: '', date: '', credentialUrl: '' }] })}
        onRemove={(id) => patch({ certifications: items.filter((x) => x.id !== id) })}
        onChange={(id, p) => change(id, p)}
        addLabel="Add Certification"
        collapsible={false}
        render={(item) => (
          <div className="grid gap-4 sm:grid-cols-2">
            <TextField label="Certification" value={item.name} onChange={(e) => change(item.id, { name: e.target.value })} />
            <TextField label="Issuing Organization" value={item.organization} onChange={(e) => change(item.id, { organization: e.target.value })} />
            <input type="month" value={item.date ?? ''} onChange={(e) => change(item.id, { date: e.target.value })} className="focus-ring h-10 rounded-md border border-border-strong bg-surface-2 px-3 text-sm text-foreground" aria-label="Date" />
            <TextField label="Credential URL" optional value={item.credentialUrl} onChange={(e) => change(item.id, { credentialUrl: e.target.value })} />
          </div>
        )}
      />
    </EditorSection>
  )
}

export function AchievementsSection() {
  const { data, patch } = useResumeDraft()
  const items = data?.achievements ?? []
  const change = (id: string, p: Partial<AchievementItem>) =>
    patch({ achievements: items.map((x) => (x.id === id ? { ...x, ...p } : x)) })

  return (
    <EditorSection title="Achievements" icon={<Award className="size-4" />} badge={String(items.length)}>
      <Repeatable
        items={items}
        onAdd={() => patch({ achievements: [...items, { id: uid('ach'), title: '', organization: '', date: '', description: '' }] })}
        onRemove={(id) => patch({ achievements: items.filter((x) => x.id !== id) })}
        onChange={(id, p) => change(id, p)}
        addLabel="Add Achievement"
        collapsible={false}
        render={(item) => (
          <div className="grid gap-4 sm:grid-cols-2">
            <TextField label="Achievement" value={item.title} onChange={(e) => change(item.id, { title: e.target.value })} />
            <TextField label="Organization" optional value={item.organization} onChange={(e) => change(item.id, { organization: e.target.value })} />
            <input type="month" value={item.date ?? ''} onChange={(e) => change(item.id, { date: e.target.value })} className="focus-ring h-10 rounded-md border border-border-strong bg-surface-2 px-3 text-sm text-foreground" aria-label="Date" />
            <div className="sm:col-span-2">
              <TextAreaField label="Description" optional value={item.description} onChange={(e) => change(item.id, { description: e.target.value })} />
            </div>
          </div>
        )}
      />
    </EditorSection>
  )
}

/* ─── Target job ─────────────────────────────────────────────────────── */

export function TargetSection() {
  const { data, patch } = useResumeDraft()
  if (!data) return null
  return (
    <EditorSection
      title="Target Job"
      icon={<Target className="size-4" />}
      badge={data.targetJob.role ? data.targetJob.role : 'Not set'}
    >
      <div className="grid gap-4">
        <div>
          <p className="mb-1.5 text-sm font-medium text-muted">Target role</p>
          <Input
            list="role-suggestions-editor"
            value={data.targetJob.role}
            onChange={(e) => patch({ targetJob: { ...data.targetJob, role: e.target.value } })}
            placeholder="e.g. Java Backend Developer"
          />
          <datalist id="role-suggestions-editor">
            {['Software Engineer', 'Frontend Developer', 'Backend Developer', 'Full Stack Developer', 'Java Backend Developer', 'Data Analyst', 'Data Scientist', 'DevOps Engineer'].map((r) => (
              <option key={r} value={r} />
            ))}
          </datalist>
        </div>
        <div>
          <p className="mb-1.5 text-sm font-medium text-muted">Job description</p>
          <Textarea
            rows={5}
            value={data.targetJob.jobDescription}
            onChange={(e) => patch({ targetJob: { ...data.targetJob, jobDescription: e.target.value } })}
            placeholder="Paste the job description for keyword matching…"
          />
        </div>
      </div>
    </EditorSection>
  )
}

/* ─── helpers ────────────────────────────────────────────────────────── */

function resumeTextContext(data: NonNullable<ReturnType<typeof useResumeDraft>['data']>) {
  return [
    data.personal.professionalTitle,
    ...data.experience.flatMap((e) => [e.jobTitle, ...e.technologies]),
    ...data.skills.technical.flatMap((g) => g.skills),
  ].filter(Boolean).join(' ')
}